### ISSUE TITLE
수정 사항 

### ISSUE THREAD

**Issue by kwanghoon** [H-sooyeon/SmallBasic_FileList#1]
@H-sooyeon 

+절대 경로 (본인 디렉토리 구조에 의존하는 경로)를 삭제

https://github.com/H-sooyeon/SmallBasic_FileList/blob/9ff7e4446f68f7eaa5e1e0a406223579691540d4/SmallBasicText/src/TextExtract.java#L17

https://github.com/H-sooyeon/SmallBasic_FileList/blob/9ff7e4446f68f7eaa5e1e0a406223579691540d4/SmallBasicText/src/TextExtract.java#L53

+close하지 않아도 되나?

https://github.com/H-sooyeon/SmallBasic_FileList/blob/9ff7e4446f68f7eaa5e1e0a406223579691540d4/SmallBasicText/src/TextExtract.java#L30

+다운 받아 저장한 .sb 파일을 보면 줄 바꿈이 과도하게 되어 있음. 

<br />를 공백으로 바꾸어볼까?  <br />를 줄 바꿈 문자로 바꾸지 않아도 현재 읽는 방식이 바이트 단위로 읽다보니 원래 웹 페이지에 있던
줄 바꿈 문자도 그대로 읽어 .sb 파일에 쓰는 것으로 보임. 

https://github.com/H-sooyeon/SmallBasic_FileList/blob/9ff7e4446f68f7eaa5e1e0a406223579691540d4/SmallBasicText/src/TextExtract.java#L50

+내용이 error인 파일들은 아예 만들지 않는 것으로 할까요?

존재하지 않는 ID는 추출과정에서 에러가 떠서 제가 없앴는데, "error"라고 저장되어있는 파일들은 추출 후에 확인과정에서 알게 되어 일단 가지고 있어요
예외처리 추가해서 파일 추출 다시 할 수 있으니, 혹시 없애는 것이 좋다고 생각드시면 말씀해주세요!

**Comment by H-sooyeon** [comment]
수정해서 재 업로드 했어요!

close 없애고 추출해봤는데 파일 데이터가 저장이 안돼서 그대로 뒀어요

**Comment by kwanghoon** [comment]
@H-sooyeon :+1:
